version: 2
jobs:
  build:
    working_directory: ~/mangaki/mangaki
    docker:
      - image: circleci/python:3.6-stretch-browsers
      - image: circleci/postgres:9.6.10-alpine-ram
        environment:
          POSTGRES_USER: mangaki
          POSTGRES_DB: circle_test
    environment:
      TEST_REPORTS: /tmp/test-reports
      ARTIFACTS: /tmp/artifacts
      MATPLOTLIBRC: tests
    steps:
      - checkout:
          path: ~/mangaki
      - restore_cache:
          key: deps-{{ .Branch }}-{{ checksum "~/mangaki/requirements/dev.txt" }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common python-dev libopenblas-dev postgresql-client
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install numpy>=1.13  # Necessary for Surprise…
          pip install -r ~/mangaki/requirements/dev.txt
      - save_cache:
          key: deps-{{ .Branch }}-{{ checksum "~/mangaki/requirements/dev.txt" }}
          paths:
            - "venv"
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: |
          psql -h localhost -U mangaki -d circle_test -c "create extension if not exists pg_trgm;
                                create extension if not exists unaccent"
          cp ~/mangaki/.circle_mangaki_settings.ini settings.ini
          . venv/bin/activate
          python manage.py migrate
          python manage.py ranking
          python manage.py top --all
          mkdir -p $TEST_REPORTS
          mkdir -p $ARTIFACTS
          python manage.py collectstatic --no-input
          mkdir -p $TEST_REPORTS/django
          coverage run manage.py test --with-xunit --xunit-file=$TEST_REPORTS/django/nosetests.xml --logging-clear-handlers
          coverage html -d $ARTIFACTS
          bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/test-reports

  push_beta:
    docker:
      - image: williamyeh/ansible:ubuntu16.04
    working_directory: ~/mangaki
    steps:
      - checkout:
          path: ~/mangaki
      - run:
          name: Setup environment
          command: |
            apt-get update
            apt-get install python3
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install ansible
      - run:
          name: Deploying the beta instance using Ansible
          command: |
            . venv/bin/activate
            ./provisioning/scripts/deploy_beta.sh
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - push_beta:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - raito/cci2-deploy
