version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-browsers
      - image: circleci/postgres:9.6.2-alpine-ram
        environment:
          POSTGRES_USER: mangaki
          POSTGRES_DB: circle_test
    environment:
      TEST_REPORTS: /tmp/test-reports
      ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common python-dev libopenblas-dev postgresql-client
          sudo apt-add-repository ppa:ansible/ansible -y
          sudo apt-get update
          sudo apt-get install -y ansible
          pip install --upgrade pip
          pip install numpy>=1.13  # Necessary for Surprise…
          pip install -r requirements/dev.txt
          psql -d circle_test -c "create extension if not exists pg_trgm;
                                create extension if not exists unaccent"
          cp .circle_mangaki_settings.ini mangaki/settings.ini
          python mangaki/manage.py migrate
          python mangaki/manage.py ranking
          python mangaki/manage.py top --all
          mkdir -p $TEST_REPORTS
          mkdir -p $ARTIFACTS
          python manage.py collectstatic --no-input
          mkdir -p $TEST_REPORTS/django
          coverage run manage.py test --with-xunit --xunit-file=$TEST_REPORTS/django/nosetests.xml --logging-clear-handlers
          coverage html -d $ARTIFACTS
          bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/test-reports

  push_beta:
    machine: true
    steps:
      - run: |
          sudo apt-get update
          sudo apt-add-repository ppa:ansible/ansible -y
          sudo apt-get update
          sudo apt-get install -y ansible
          pip install --upgrade pip
      - deploy: ./provisioning/scripts/deploy_beta.sh
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - push_beta:
          requires:
            - build
          filters:
            branches:
              only: master
