version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6-stretch-browsers
      - image: circleci/postgres:9.6.10-alpine-ram
        environment:
          POSTGRES_USER: mangaki
          POSTGRES_DB: circle_test
    environment:
      TEST_REPORTS: /tmp/test-reports
      ARTIFACTS: /tmp/artifacts
    steps:
      - checkout
      - restore_cache:
        key: deps-{{ Branch }}-{{ checksum "requirements/dev.txt" }}
      - run: |
          sudo apt-get update
          sudo apt-get install -y software-properties-common python-dev libopenblas-dev postgresql-client
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install numpy>=1.13  # Necessary for Surprise…
          pip install -r requirements/dev.txt
      - save_cache:
        key: deps-{{ Branch }}-{{ checksum "requirements/dev.txt" }}
        paths:
          - "venv"
      - run:
          name: Waiting for Postgres to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for Postgres && exit 1
      - run: |
          psql -h localhost -U mangaki -d circle_test -c "create extension if not exists pg_trgm;
                                create extension if not exists unaccent"
          cp .circle_mangaki_settings.ini mangaki/settings.ini
          . venv/bin/activate
          python mangaki/manage.py migrate
          python mangaki/manage.py ranking
          python mangaki/manage.py top --all
          mkdir -p $TEST_REPORTS
          mkdir -p $ARTIFACTS
          cd mangaki && python manage.py collectstatic --no-input
          mkdir -p $TEST_REPORTS/django
          cd mangaki && coverage run manage.py test --with-xunit --xunit-file=$TEST_REPORTS/django/nosetests.xml --logging-clear-handlers
          cd mangaki && coverage html -d $ARTIFACTS
          cd mangaki && bash <(curl -s https://codecov.io/bash)
      - store_artifacts:
          path: /tmp/artifacts
          destination: build
      - store_test_results:
          path: /tmp/test-reports

  push_beta:
    machine: true
    steps:
      - run: |
          sudo pip install --upgrade pip
      - deploy: ./provisioning/scripts/deploy_beta.sh
workflows:
  version: 2
  build_and_test_and_deploy:
    jobs:
      - build
      - push_beta:
          requires:
            - build
          filters:
            branches:
              only: master
